import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { LayoutDashboard, ShoppingCart, BookOpen, Wallet, Package } from "lucide-react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SAQR Wholesale POS",
    description: "نظام إدارة محلات الخضار والفواكه بالجملة",
    };

    export default function RootLayout({
      children,
      }: Readonly<{
        children: React.ReactNode;
        }>) {
          return (
              <html lang="ar" dir="rtl">
                    <body className={`${inter.className} bg-slate-900 text-slate-100 min-h-screen flex flex-col md:flex-row`}>
                            
                                    {/* شريط التنقل - متوافق مع الجوال (علوي) ومع اللابتوب (جانبي) */}
                                            <nav className="bg-slate-800 border-b md:border-b-0 md:border-l border-slate-700 w-full md:w-64 flex md:flex-col justify-between md:justify-start p-4 sticky top-0 z-50 overflow-x-auto md:overflow-x-visible whitespace-nowrap md:whitespace-normal scrollbar-none gap-2">
                                                      <div className="text-xl font-bold text-emerald-400 hidden md:block mb-8 text-center border-b border-slate-700 pb-4">
                                                                  🍉 نظام صقر للجملة
                                                                            </div>
                                                                                      
                                                                                                <div className="flex md:flex-col gap-1 w-full">
                                                                                                            <Link href="/" className="flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-slate-700 text-slate-300 hover:text-emerald-400 transition-colors">
                                                                                                                          <LayoutDashboard className="w-5 h-5" />
                                                                                                                                        <span className="text-sm font-medium">الرئيسية</span>
                                                                                                                                                    </Link>
                                                                                                                                                                
                                                                                                                                                                            <Link href="/pos" className="flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-slate-700 text-slate-300 hover:text-emerald-400 transition-colors">
                                                                                                                                                                                          <ShoppingCart className="w-5 h-5" />
                                                                                                                                                                                                        <span className="text-sm font-medium">فاتورة مبيعات</span>
                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                            <Link href="/ledger" className="flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-slate-700 text-slate-300 hover:text-emerald-400 transition-colors">
                                                                                                                                                                                                                                                          <BookOpen className="w-5 h-5" />
                                                                                                                                                                                                                                                                        <span className="text-sm font-medium">دفتر الحسابات</span>
                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                            <Link href="/receipts" className="flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-slate-700 text-slate-300 hover:text-emerald-400 transition-colors">
                                                                                                                                                                                                                                                                                                                          <Wallet className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                        <span className="text-sm font-medium">سندات القبض</span>
                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                            <Link href="/inventory" className="flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-slate-700 text-slate-300 hover:text-emerald-400 transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                          <Package className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-sm font-medium">المخزن والجرد</span>
                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* محتوى الشاشات المتغير */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <main className="flex-1 p-4 md:p-8 overflow-y-auto max-w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {children}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
