"use client";
import React, { useState } from "react";
import { TrendingUp, Users, ArrowUpRight, ArrowDownRight, PackageCheck } from "lucide-react";
import Link from "next/link";

export default function Dashboard() {
  // بيانات تجريبية مؤقتة للشاشة لحين ربط الـ Fetch النهائي مع الـ API
    const [stats] = useState({
        todaySales: 4520, // شيكل
            totalDebts: 18450,
                cashReceived: 3100,
                    lowStockCount: 3,
                      });

                        return (
                            <div className="space-y-6">
                                  {/* هيدر ترحيبي */}
                                        <div className="flex justify-between items-center bg-slate-800 p-6 rounded-2xl border border-slate-700 shadow-lg">
                                                <div>
                                                          <h1 className="text-2xl font-bold text-slate-100">مرحباً بك في نظام صقر لإدارة الجملة 👋</h1>
                                                                    <p className="text-slate-400 text-sm mt-1">إليك نظرة عامة على حركة البيع والحسابات لليوم.</p>
                                                                            </div>
                                                                                  </div>

                                                                                        {/* كروت الإحصائيات السريعة */}
                                                                                              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                                                                                                      
                                                                                                              <div className="bg-slate-800 p-5 rounded-xl border border-slate-700 flex items-center justify-between">
                                                                                                                        <div>
                                                                                                                                    <p className="text-sm text-slate-400 font-medium">مبيعات اليوم</p>
                                                                                                                                                <p className="text-2xl font-bold text-emerald-400 mt-1">{stats.todaySales} ₪</p>
                                                                                                                                                          </div>
                                                                                                                                                                    <div className="p-3 bg-emerald-500/10 rounded-lg text-emerald-400">
                                                                                                                                                                                <TrendingUp className="w-6 h-6" />
                                                                                                                                                                                          </div>
                                                                                                                                                                                                  </div>

                                                                                                                                                                                                          <div className="bg-slate-800 p-5 rounded-xl border border-slate-700 flex items-center justify-between">
                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                <p className="text-sm text-slate-400 font-medium">إجمالي الديون المعلقة</p>
                                                                                                                                                                                                                                            <p className="text-2xl font-bold text-rose-400 mt-1">{stats.totalDebts} ₪</p>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                <div className="p-3 bg-rose-500/10 rounded-lg text-rose-400">
                                                                                                                                                                                                                                                                            <Users className="w-6 h-6" />
                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                      <div className="bg-slate-800 p-5 rounded-xl border border-slate-700 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                            <p className="text-sm text-slate-400 font-medium">الكاش المحصل اليوم</p>
                                                                                                                                                                                                                                                                                                                                        <p className="text-2xl font-bold text-blue-400 mt-1">{stats.cashReceived} ₪</p>
                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                            <div className="p-3 bg-blue-500/10 rounded-lg text-blue-400">
                                                                                                                                                                                                                                                                                                                                                                        <ArrowDownRight className="w-6 h-6" />
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-slate-800 p-5 rounded-xl border border-slate-700 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-slate-400 font-medium">أصناف أوشكت على النفاد</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-2xl font-bold text-amber-400 mt-1">{stats.lowStockCount} أصناف</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-3 bg-amber-500/10 rounded-lg text-amber-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <PackageCheck className="w-6 h-6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* أزرار الوصول السريع للميدان */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-slate-800 p-6 rounded-2xl border border-slate-700 space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-lg font-semibold text-slate-200">إجراءات سريعة في ساحة المحل</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/pos" className="p-4 bg-emerald-600 hover:bg-emerald-500 rounded-xl text-center font-medium transition-colors shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ➕ فاتورة بيع جديدة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/receipts" className="p-4 bg-blue-600 hover:bg-blue-500 rounded-xl text-center font-medium transition-colors shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              💵 قبض دفعة كاش
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/ledger" className="p-4 bg-slate-700 hover:bg-slate-600 rounded-xl text-center font-medium transition-colors shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              📖 دفتر الحسابات
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/inventory" className="p-4 bg-amber-600 hover:bg-amber-500 rounded-xl text-center font-medium transition-colors shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              📦 جرد وتعديل المخزن
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            